### ISSUE TITLE
Docker image fails to start - ModuleNotFoundError: No module named 'ahocorapy'

### ISSUE THREAD

**Issue by unickq** [LuteOrg/lute-v3#490]
**Description**

On docker compose up for 
```yml
services:
  lute:
    image: jzohrab/lute3:latest
    ports:
      - 5010:5000
    volumes:
      - ./data:/lute_data
      - ./backups:/lute_backup
```
Log
```bash
Attaching to lute-1
lute-1  | Traceback (most recent call last):
lute-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
lute-1  |   File "<frozen runpy>", line 88, in _run_code
lute-1  |   File "/usr/local/lib/python3.11/site-packages/lute/main.py", line 17, in <module>
lute-1  |     from lute.app_factory import create_app
lute-1  |   File "/usr/local/lib/python3.11/site-packages/lute/app_factory.py", line 30, in <module>
lute-1  |     import lute.db.demo
lute-1  |   File "/usr/local/lib/python3.11/site-packages/lute/db/demo.py", line 14, in <module>
lute-1  |     from lute.book.stats import refresh_stats
lute-1  |   File "/usr/local/lib/python3.11/site-packages/lute/book/stats.py", line 6, in <module>
lute-1  |     from lute.read.render.service import get_multiword_indexer, get_textitems
lute-1  |   File "/usr/local/lib/python3.11/site-packages/lute/read/render/service.py", line 12, in <module>
lute-1  |     from lute.read.render.multiword_indexer import MultiwordTermIndexer
lute-1  |   File "/usr/local/lib/python3.11/site-packages/lute/read/render/multiword_indexer.py", line 5, in <module>
lute-1  |     from ahocorapy.keywordtree import KeywordTree
lute-1  | ModuleNotFoundError: No module named 'ahocorapy'
lute-1 exited with code 1
```

**Comment by thelazyoxymoron** [comment]
Facing the same issue

**Comment by unickq** [comment]
@thelazyoxymoron the solution for now is to use older version
```yml
services:
  lute:
    image: jzohrab/lute3:3.5.3
    ports:
      - 5010:5000
    volumes:
      - ./data:/lute_data
      - ./backup:/lute_backup
```

But @jzohrab, please check your recent changes in 3.5.4 and 3.5.5
